### ISSUE TITLE
Training more models to the same .yml file..

### ISSUE THREAD

**Issue by saishreddyk** [pydeveloperashish/Face-Recognition#3]
Can we train more models to the already trained .yml file?, by still retaining the old data in the file rather than overwriting?

**Comment by ghost** [comment]
@saishreddyk be careful of Ashish, he is a potential criminal
![YKNh9NG](https://user-images.githubusercontent.com/85831260/121807266-f8b10700-cc85-11eb-8538-bea696ee9fed.jpeg)
![C4er0VX](https://user-images.githubusercontent.com/85831260/121807272-fa7aca80-cc85-11eb-8e38-27189fa8365b.jpeg)
